version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: signal-belive-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signal_belive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: signal-belive-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass redis_password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'redis_password', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: signal-belive-api
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production
  #     - IS_API=1
  #     - IS_WORKER=0
  #     - APP_ENV=production
  #     - PORT=3000
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_DATABASE=signal_belive
  #     - DB_SYNC=1
  #     - DB_DEBUG=1
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_DATABASE=0
  #     - REDIS_URL=redis://:redis_password@redis:6379
  #     - REDIS_PASSWORD=redis_password
  #     - REDIS_FAMILY=0
  #     - JWT_SECRET=super_secret_key
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signal-belive-worker
    restart: always
    environment:
      - NODE_ENV=production
      - IS_API=0
      - IS_WORKER=1
      - APP_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=signal_belive
      - DB_SYNC=1
      - DB_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_URL=redis://:redis_password@redis:6379
      - REDIS_PASSWORD=redis_password
      - REDIS_FAMILY=0
      - JWT_SECRET=super_secret_key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
