targetPort: 3000

ingress:
  enable: true
  host: nestjs-template-server-dev.dev

envFrom:
  configMaps:
    - name: dev-common
    - name: dev-postgres
    - name: dev-redis
    - name: dev-milvus

resources:
  requests:
    cpu: '50m'
    memory: '200Mi'
  limits:
    cpu: '200m'
    memory: '400Mi'

workers:
  - name: nestjs-template-worker
    replicas: 1
    envFrom:
      configMaps:
        - name: nestjs-template-worker
    resources:
      requests:
        cpu: '50m'
        memory: '200Mi'
      limits:
        cpu: '200m'
        memory: '400Mi'

healthCheck:
  enable: true
  path: /health
