name: Deploy to Railway (Develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: app-service
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}

